name: idiom_puzzle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/favicon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/icon/favicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/favicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/favicon.png
    - assets/audio/click.wav
    - assets/audio/success.wav
    - assets/audio/error.wav